### ISSUE TITLE
DreamerNX chamber fan not working properly in v0.9.2

### ISSUE THREAD

**Issue by Lucien-X** [moonglow/FlashForge_Marlin#25]
Just flashed 0.9.2 firmware , the cooling fans on the back of chamber is not working right.

There are two of them , but when I  adjust 'Fans Speed 3' manually , only one of them is spining as I wish.

**Comment by moonglow** [comment]
This fans connected to ONE output it not controlled separately. To make sure what you disable automatic chamber fan control, please set chamber temp to 0 ( it sets to 45 by default ) and then try to test FAN3 control. I recommend to set it to 100% and if your second fan is stuck, try to turn it by hand and this try again. I do not know why one of them is works such they, because where is not other output. Maybe one of fan does not like PWM or something like that.

**Comment by Lucien-X** [comment]
False alert, the same shit happens when I roll back to original firmware.
Gotta be the hardware problem. I'll enquiry the seller about this.

**Comment by Lucien-X** [comment]
Nailed it, the PWM signal is intact , proved that with a n alternative fan from my PC.
Gotta order a new 8015 fan to replace that broken one.

![wire](https://user-images.githubusercontent.com/20273998/117671707-ac346080-b1db-11eb-8d58-17357d038d91.jpg)
![fans](https://user-images.githubusercontent.com/20273998/117672003-fd445480-b1db-11eb-92df-4717ad2cf2c4.jpg)

![rewired](https://user-images.githubusercontent.com/20273998/117671726-b0f91480-b1db-11eb-9221-f180ddcb7ce6.jpg)

**Comment by moonglow** [comment]
@Lucien-X RGB fan looks much better )

**Comment by Lucien-X** [comment]
> @Lucien-X RGB fan looks much better )

But the LED units produce extra distraction , when I wanna get a precise picture about my print.
And of course, extra heat .

Besides, the RGB fan is only for test, the working voltage and size of it is not compatible for the printer.
