### ISSUE TITLE
Max temp 265 ?

### ISSUE THREAD

**Issue by exxosuk** [moonglow/FlashForge_Marlin#60]
It is not really a issue as such.. But is there a way to increase this value to something like 300c ? I assume this is a firmware issue which I am struggling to compile myself currently :(

**Comment by moonglow** [comment]
Yep you can edit the firmware configuration file  `Configuration.h`, but you must fully understand why you need this, because overtemp can melt some plastic parts or internal PTFE tube in stock extruder. By default temperature sets to 280 ( with 15 degrees overshoot ) it will give us max nominal temp as 265C. So you need to sets it to 315 to get 300C ;)

p.s: i also answered to you in discussion thread about firmware building process.
